apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v1
  labels:
    app: helloworld-node
    version: v1
spec:
  selector:
    matchLabels:
      app: helloworld-node
      version: v1
  template:
    metadata:
      labels:
        app: helloworld-node
        version: v1
    spec:
      containers:
      - name: helloworld-node
        image: hashicorp/http-echo:latest
        args: ["-listen=:8080", "-text=Hello from hello-v1!"] 
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-v1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
  labels:
    pp: helloworld-node
    version: v2
spec:
  selector:
    matchLabels:
      app: helloworld-node
      version: v2
  template:
    metadata:
      labels:
        app: helloworld-node
        version: v2
    spec:
      containers:
      - name: helloworld-node
        image: hashicorp/http-echo:latest
        args: ["-listen=:8080", "-text=Hello from hello-v1!"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-v2-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-v2
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
# Service for hello-v1 Deployment, annotated to use the BackendConfig
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-v1
  annotations:
    cloud.google.com/backend-config: '{"default": "helloworld-backend-config"}'
spec:
  selector:
    app: helloworld-node
    version: v1 # This service only targets v1 pods
  ports:
    - protocol: TCP
      name: http # Name the port for BackendConfig reference
      port: 80
      targetPort: 8080
  type: ClusterIP
---
# Service for hello-v2 Deployment (no BackendConfig annotation needed here)
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-v2
spec:
  selector:
    app: helloworld-node
    version: v2
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.gke.io/v1
kind: ServiceGroup
metadata:
  name: helloworld-service-group
spec:
  # Define the weighted backend services
  services:
    - name: helloworld-service-v1
      weight: 50
    - name: helloworld-service-v2
      weight: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress # Keep the same name to update the existing Ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    # IMPORTANT: The BackendConfig annotation should now point to the ServiceGroup BackendConfig,
    # or you can remove it if the BackendConfig only contained features for the single service.
    # For ServiceGroups, health checks are typically defined within the ServiceGroup's services.
    # For simplicity for this weighted demo, we will remove the backend-config annotation for now.
    # If you need specific BackendConfig features (e.g., CDN, custom headers) for the *Ingress path*,
    # you'd re-add it pointing to a BackendConfig that applies to the ServiceGroup itself.
    #
    # Let's keep the existing BackendConfig for now, as it defines a health check,
    # but understand it primarily applies to helloworld-service-v1 if it was the defaultBackend.
    # When using ServiceGroup, health checks are often defined per service within the group.
    # Let's remove the BackendConfig annotation from the Ingress for cleaner behavior with ServiceGroup.
    # cloud.google.com/backend-config: '{"default": "helloworld-backend-config"}' # <-- REMOVE THIS LINE
spec:
  # The defaultBackend now points to the ServiceGroup
  defaultBackend:
    service:
      name: helloworld-service-group # <-- Pointing to the ServiceGroup
      port:
        number: 80